peer:
        build: .
        links:
                - zookeeper
        environment:
                - ZOOKEEPER_ADDR=zookeeper:2181
                - ONYX_ID=1
                - NPEERS=4
        privileged: true

zookeeper:
        image: 'mesoscloud/zookeeper:3.4.6-ubuntu-14.04'
        environment:
                - MYID=1
        expose:
                - '2181'
        ports:
                - '2181:2181'
